### ISSUE TITLE
Run V8 tests on Android

### ISSUE THREAD

**Issue by kalmard** [v8mips/v8mips#10]
test.py has an android runner (not yet submitted to Google) that allows running any V8 test on android painlessly.

Usage:
tools/test.py <usual flags> --no-build --android --android-push-path=<tmp dir on device/emulator> --android-bin-path=<path to d8 and cctest on device/emulator>

Obviously d8 and cctest need to be accessable on the device by pre-copying them or mounting an nfs share.
--android-bin-path can be ommitted, in which case the test runner will try to find the executables under --android-push-path.

busybox is also needed on the device (in $PATH).

Akos, please verify this information and put it in a wiki page to make it permanent (after possibly correcting it).

**Comment by sunnyshines2008** [comment]
I am trying to run the v8 tests on android device for v8 3.9
But i get following error with the above mentioned method.

> > > test.py: error: no such option: --android

Can you please tell me where i can get the android runner??

**Comment by kisg** [comment]
The android runner is included here in the v8m-rb repository on the bleeding_edge branch.

Some usage examples:

 a) mount your v8 workspace over NFS onto the Android device to the same path where the workspace is on the host. The following command will work in this case, it will use the binaries and test files from your workspace directly and execute the actual commands using adb shell.

tools/test.py --mode=release --verbose --timeout=480 --arch=mips --report --android cctest

 b) If you set up NFS like above, but want to use the binaries from a different directory (e.g. because you want to use the binaries built by the android build system), then you have to specify --android-bin-path like this:

tools/test.py --mode=release --verbose --timeout=480 --arch=mips --report --android --android-bin-path /tmp/abins cctest

 c) If you don't want to or cannot set up NFS, you have to use --android-push-path to push your test files and binaries using adb push prior to running the tests:

tools/test.py --mode=release --verbose --timeout=480 --arch=mips --report --android --android-push-path /tmp/palfia cctest

 d) If you want, you can use binaries from a different directory, while using adb push to send over the test files, just specify both --android-push-path and --android-bin-path:

tools/test.py --mode=release --verbose --timeout=480 --arch=mips --report --android --android-push-path /tmp/palfia --android-bin-path /tmp/abins cctest

Please let us know if you have any issues with this.

**Comment by sunnyshines2008** [comment]
Hello kisg,
Is this android runner specific to bleeding edge?
I want to run the tests on the android device for v8 3.9 also.
Is this android runner a file or directory that i could copy and use in my 3.9 build too?

**Comment by kisg** [comment]
It is a set of patches to v8:
https://github.com/paul99/v8m-rb/commit/a9aed8932c8778d68c263c6d896e7aeaed9191b8
https://github.com/paul99/v8m-rb/commit/559829ad06e5b0511a95bf6a47953a9799be5ddf
https://github.com/paul99/v8m-rb/commit/1a777ff144465e5279b6aacf81b3093d6904a234

If you apply these patches to your tree, you should be able to use the android runner.

**Comment by sunnyshines2008** [comment]
Thanks kisg, I can now run the test suites on my android device both for v8 3.9 and bleeding edge, though many of them are failing.

**Comment by sunnyshines2008** [comment]
Hello Kisg,
I am currently facing some failed test cases. If you have any idea about it please help.

The test for the PREPARSER test cases are failing so i am running only the preparser tests on my android device. I have already pushed preparser from 'out/android.release/' in the android-bin-path.

Some test cases pass(of preparser) execute fine and at one(strict-octal-regexp), the test stops saying :-

> > [00:01|%   0|+  12|-   0]: release preparser strict-octal-regexp  
> > 'User pressed CTRL+C or IO went wrong'

I removed this test case and i found, similar error on duplicate-parameter.pyt file.           

> > [00:01|%   0|+  17|-   0]: release duplicate-parameter dups 
> > 'User pressed CTRL+C or IO went wrong'

So, i individually executed the cases in 'duplicate-parameter.pyt' via command like :-

adb shell (android-push-path)/data/v8/adb.retval (android-bin-path)/data/d8/preparser -e ""use strict";    function foo(a, \u0061) {  } " throws strict_param_dupe --test

And, it fails. Interesting thing is that the above test command also fails for native/preparser. 
But, if i remove 'throws strict_param_dupe' from the test cases, majority of them pass with RETVAL: 0.

I assume, that the expected outcome of the test cases is fail and the test.py is handling it well for the Host system. Thats why all my test cases pass for Host device. And probably i need to have some modification in my test.py, so that it also takes these fail test cases as pass.

Please suggest, if i am on track or is it the wrong direction.

**Comment by kisg** [comment]
Closed due to inactivity. Please reopen if issue is still relevant.
