### ISSUE TITLE
Investigate using out of line const pool for MIPS similar to ARM / PPC

### ISSUE THREAD

**Issue by kalmard** [v8mips/v8mips#13]
Running a crude simulator test reveals that a major portion of executed code (10-15% in debug mode) is lui+ori.

While this may prove to be a lot of work, the speed benefits may be worth it. Here are a few ideas:
1. using the root array or a similar, MIPS-only array to hold our constants
2. using a const pool like on ARM, per-function or per-assembler, loading its address at the beginning and storing it in a dedicated register

A few things to remember:
This only affects constants that don't fit into any instruction's 16 bit immediate slot, but this includes all pointers.
t9 is used very often to hold function addresses. If handled carefully, it could be used as a per-function global pointer.
s0-s7 are mostly unutilized in MIPS code, aren't they?
Constant values can be re-used unless marked specially (RelocInfo, code patching), but linear search on a large array may consume too much time (not an issue when generating snapshot).
The GC has to be updated for any of the solutions. However since MIPS is so unique, the GC is already very flexible.
The serializer has to be updated as well.
Constant patching (especially from genearated code) has to be updated.
lw can take a negative immediate (offset) as well, so the array could be indexed from the middle.

I'm not sure about this, but I remember reading that on some MIPS CPUs using the register loaded (via lw) in the previous instruction stalls the pipeline, so maybe there would be absolutely no benefit from this.

**Comment by paul99** [comment]
I really appreciate the gathering of the data that this is 10-15% of out instruction load. That makes this an attractive optimization candidate. 

As you point out, it is a lot of work to change this. Wondering if there is any short-cut that could allow us to prototype & benchmark this without having to do it 100% and get GC working, etc. But I suppose just about any prototype would have to allow code-patching, and then we are 90% of the way to working under GC.

Possibly we could micro-benchmark relative load via reg, versus lui/ori. But cache behavior would be very different, and harder to predict.

I will start by talking to the chip architects, and see if they have a feel for which would run faster.

**Comment by paul99** [comment]
I spoke with Wayne from the micro-arch group, and pointed out that a lw(register, offset) has a load-to-use delay, that can be 3 or 4 clocks, whereas with the li macro (lui/ori combination) data should be available at the next instruction.

We certainly have no real instruction scheduling, and a cursory inspection shows lots of li() usage where the next instruction uses the data. (the better out-of-order cores will try to work around this)

So in a simple case, where everything hits the cache, the current lui/ori should be faster. 

However, the cache usage would be very different in these 2 scenarios, I think it impossible to predict, and a cache performance improvement or degradation could easily dominate the load-to-use issue.

To be clear, the liu/ori data is from the instruction cache. The 2 instructions take more space in the cache than the single lw() instruction would. For lw(reg, offset), the 'constant-pool' like data would be cached in the data cache, and we have nothing like that now. So I-cache perf could be a little better, and maybe the data-cache perf would be a little worse.

We also have to load the const-pool address, since we do not have pc-relative loads. 

I just realized now that there is a complication for long functions that have multiple constant-pool entries. We have to load the pointer register multiple times. And another complication is save/restore across every call. Hmm, this last sounds like performance killer to me. 

Maybe someone can think of a way around this? Thoughts?

**Comment by paul99** [comment]
I will leave this open for consideration. I think it's not too likely to help for the reasons stated above. 

However, both ARM & PPC implement out-of-line const pool now, and I have not looked into its applicability for MIPS. r6 instruction set also has some pc-relative load instructions which could help with the traditional in-line constant pool.

**Comment by kisg** [comment]
Implementing (or first investigating) an out of line const pool is a good idea, renaming it to reflect this.

**Comment by ibogosavljevic** [comment]
We implemented constant pools on R6 and Octane showed slow-down of about 5%. We speculate that the problem is related to cache misses that happen in this case, that is to say, LUI/ORI are already in instruction cache, so no problem here, however LDPC can access any part of memory not necessary in data cache.

I would expect similar behavior on R2 with the difference that R2 requires one more register to keep the address of constant pool.
