### ISSUE TITLE
benchmark flakiness and bugs on mips32

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#145]
When doing octane tests for #_octeon3_ channel I saw a failure on mips32 for pdfjs, and a really bad score for Box2D. Those first results posted below.

When I look at the benchmarks tests, it is terrible, lots of flakes and crashes since mid-last week (I took my eye off the ball on these tests). https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20benchmarks?numbuilds=100  It's also possible that there is something wrong with the CI-20 board that is running the tests. Please re-run on your own side.

Ilija, can you please do a first-stage regression/bisect, and try and find out what commit first caused these problems, and what if any made them worse? When we understand the commits that cause the problems, we can re-assign the bug-fixing as needed.

We do know that we have the unaligned doubles thing in mips32, and to even get the scores I have I pasted in Balázs 'quick-fix' from https://github.com/paul99/v8m-rb/issues/143

It is conceivable that this deopt change affected some other things, or maybe it is unrelated.

this shows the two octane problems mentioned above:

```
Richards: 3516
DeltaBlue: 5607
Crypto: 2692
RayTrace: 5065
EarleyBoyer: 4768
RegExp: 557
Splay: 996
SplayLatency: 2691
NavierStokes: 1942
PdfJS: ReferenceError: console is not defined
Mandreel: 2223
MandreelLatency: 5436
Gameboy: 5800
CodeLoad: 2537
Box2D: 27.6
zlib: 8263
Typescript: 4516
```

**Comment by ilijapavlovic** [comment]
Testing/investigation is done on the CI-20 board.

The first commit where the problem is detected during running Octane
benchmark is:
- e044f0a67e03ad55d447d0a28cc227587515bc5b
- "[deoptimizer] Remove uses of TranslationIterator outside the deoptimizer."

According to description, expected problems are "PdfJS: ReferenceError: console is not defined" and bad performance results for the Box2D benchmark.

Here is one example of the Octane's output:

```
  Richards: 1952
  DeltaBlue: 1521
  Crypto: 1515
  RayTrace: 2202
  EarleyBoyer: 2537
  RegExp: 208
  Splay: 846
  SplayLatency: 2498
  NavierStokes: 1113
  PdfJS: 625
  Mandreel: 748
  MandreelLatency: 1903
  Gameboy: 1643
  CodeLoad: 947
  Illegal instruction
```

The PdfJS has valid score result, but the Box2D has "Illegal instruction".
The similar results were also for the commit 65b6cef8ebd06c4ddd8fd954536a15d3c806ea2d
(build #2922).

After many attempts, it was not possible to reproduce described problems
in the ticket.

After applying the patch "MIPS: Fix unaligned memory access." (https://codereview.chromium.org/1193433002)
which is already in "master" (landed CL), the problems disappeared:

```
$ ../v8/out/mipsel.release/d8 run.js

Richards: 1970
DeltaBlue: 1435
Crypto: 1516
RayTrace: 2195
EarleyBoyer: 2493
RegExp: 201
Splay: 1917
SplayLatency: 3878
NavierStokes: 1118
PdfJS: 562
Mandreel: 787
MandreelLatency: 1787
Gameboy: 1705
CodeLoad: 938
Box2D: 779
zlib: 4117
Typescript: 1445

Score (version 9): 1377
```

```
$ ./tools/run-tests.py ... --report benchmarks

[12:50|% 100|+ 110|-   0]: Done                    

--- Total time: 12:50.669 ---
   1 (06:56.361) benchmarks/octane/mandreel
   2 (05:56.010) benchmarks/kraken/imaging-gaussian-blur
   3 (04:41.569) benchmarks/octane/crypto
   4 (03:46.283) benchmarks/octane/typescript
   5 (02:36.942) benchmarks/octane/raytrace
   6 (02:12.567) benchmarks/octane/earley-boyer
   7 (01:50.451) benchmarks/octane/box2d
   8 (01:47.828) benchmarks/octane/pdfjs
   9 (01:38.330) benchmarks/octane/gbemu-part1
  10 (01:35.970) benchmarks/kraken/audio-oscillator
  11 (01:35.864) benchmarks/octane/typescript
  12 (01:35.360) benchmarks/kraken/ai-astar
  13 (01:33.355) benchmarks/kraken/imaging-desaturate
  14 (01:30.032) benchmarks/kraken/imaging-darkroom
  15 (01:18.002) benchmarks/kraken/audio-dft
  16 (01:15.171) benchmarks/octane/regexp
  17 (01:14.331) benchmarks/octane/navier-stokes
  18 (01:13.722) benchmarks/octane/mandreel
  19 (01:07.107) benchmarks/kraken/stanford-crypto-aes
  20 (01:05.983) benchmarks/octane/zlib
```

The PdfJs benchmark is executed without problems and 
the Box2D benchmark has good results.

**Comment by paul99** [comment]
As Ilija mentioned, fixed by https://codereview.chromium.org/1193433002 https://crrev.com/0acc511e62fbd717e335c700012de47827fe0630 from Balázs. Closing.
