### ISSUE TITLE
Random failures of test262: 11.3.2_TRP, 9.2.5_11_g_ii_2

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#158]
These tests have been failing periodically across several builders. I've only seen it on hardware bots, but on mipsel, mips64el, and mipsel-r1

It uses in Intl / itu stuff. Possibly an itu version problem?

(Note that big-endian runs --no-i18n, so will not run these)

Examples:
    https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20test262/builds/3175
    https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20test262/builds/1577
    https://v8.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge%20-%20test262%20-%20mipsr1/builds/2434

**Comment by paul99** [comment]
I ran these two tests individually on error-8 board, running mipsel.release and mipsel.debug (where random fails have been noted on the bots). And they both passed thousands of iterations.

Build was from my workstation, using 4.9.2 gcc. 

So there is either a config issue on the bots, or this is some complex integration problem while other tests are running.

Next step, run these tests in a loop on one core, while running t262 suite -j1 on the other core.

**Comment by ilijapavlovic** [comment]
It seems that the cause for this problem is in setting for LANG environment variable for OS on test system.
- `LANG=en_US_POSIX` : the problem will be reproduced.
- `LANG=en_US` : the test will pass.

See:
http://unicode.org/pipermail/cldr-users/2014-September/000143.html
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Locale_identification_and_negotiation

**Comment by paul99** [comment]
Ákos, can you take a look at this, with Ilija's comments  in mind. I've noticed that our boards and build machines seem to have `LANG=en_US.UTF-8`. I did not get to changing this today, and retesting. Also please see comments in 166.

I also saw that on mips32 target boards, these seemed to fail always on CI-20 boards. And builds where these tests passed were on some other board. Here are some  examples, maybe you can go thru the BB story and see if this is always true.

https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20test262/builds/3462
https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20test262/builds/3457
https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20test262/builds/3443

Never mind, here is one failing with popcorn:
https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20test262/builds/3447

**Comment by palfia** [comment]
Ilija, Thanks for the info! I can confirm that these tests pass with LANG=en_US.UTF-8 and fails with LANG= en_US_POSIX.

I've reviewed the BB results (I went through only a hundred results back) and it seems these tests constantly fail on these boards (and maybe on others):

ci20-board-1
ci20-board-2
erpro8-board-15
popcorn-hour-board-1

And always pass on these:

erpro8-board-7
erpro8-board-9
erpro8-board-10
erpro8-board-11
erpro8-board-12
erpro8-board-13
erpro8-board-14
popcorn-hour-board-2
popcorn-hour-board-3

**Comment by paul99** [comment]
@MIPSbkirby can you take a look at above LANG env-var settings, and tell us if there is any override within the BB config?

I checked this on one of the CI-20 boards yesterday, and it was set: `LANG=en_US.UTF-8`. (even for bbv8 user.) Which is the setting that should pass.

It's mysterious why some boards seem to (always? or intermittently?)  fail these tests....

**Comment by MIPSbkirby** [comment]
When I looked at builds that pass, I see the LANG=en_US.UTF-8.  And, when I looked at all the linked failing builds they all don't have LANG in the environment.  I'll get LANG=en_US.UTF-8 set on the failing boards and confirm it's set on the rest of the Buildbot slaves.

**Comment by MIPSbkirby** [comment]
The locale settings a few of the boards wasn't setup correctly.  It either didn't have en_US.UTF-8 and en_US ISO-8859-1 uncommented in /etc/locale.gen or it didn't have a LANG set in /etc/default/locale.  I've fixed this on all the boards.  Then, found all the Buildbot slaves that didn't have LANG in their environment and restarted them.  Also, I made sure the bbv8 init script gets the LANG variable into the environment from /etc/default/locale so that it's set correctly when the board reboots.  All of the Buildbot target slaves have LANG set in their environment.  So, this test should now pass.
