### ISSUE TITLE
Mozilla test fail in debug mode on simu/hw

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#16]
Today I started all test suites in debug mode on simulator and found a new failing mozilla test. It also fails on sigma8654. In release mode the test is success both on simulator and on sigma8654.

Output:

<pre>root@sigma-8654:/data/palfia/v8/v8m-rb# ./d8_g --stress-opt --always-opt --nobreak-on-abort --enable-slow-asserts --debug-code --verify-heap --expose-gc test/mozilla/mozilla-shell-emulation.js test/mozilla/data/shell.js test/mozilla/data/ecma_3/shell.js test/mozilla/data/ecma_3/Date/shell.js test/mozilla/data/ecma_3/Date/15.9.4.3.js --test
============ Stress 1/2 ============
BUGNUMBER: 363578
STATUS: 15.9.4.3 - Date.UTC edge-case arguments.
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: date 0
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: hours 0
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: minutes 0
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: seconds 0
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: milliseconds 0
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: date -1
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: hours -1
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: minutes -1
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: seconds -1
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: milliseconds -1
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: date undefined
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: hours undefined
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: minutes undefined
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: seconds undefined
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: milliseconds undefined
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: date {}
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: hours {}
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: minutes {}
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: seconds {}
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: milliseconds {}
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: date null
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: hours null
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: minutes null
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: seconds null
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: milliseconds null
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: date Infinity
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: hours Infinity
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: minutes Infinity
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: seconds Infinity
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: milliseconds Infinity
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: date -Infinity
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: hours -Infinity
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: minutes -Infinity
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: seconds -Infinity
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: milliseconds -Infinity
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: date NaN
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: hours NaN
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: minutes NaN
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: seconds NaN
 PASSED! 15.9.4.3 - Date.UTC edge-case arguments.: milliseconds NaN
============ Stress 2/2 ============

#
# Fatal error in src/mips/lithium-codegen-mips.cc, line 2166
# CHECK_EQ(3, masm()->InstructionsGeneratedSince(&done)) failed
#   Expected: 3
#   Found: 5
#

==== Stack trace ============================================

Security context: 0x2db25fb1 <JS Object>#0#
    2: /* anonymous */ [test/mozilla/data/ecma_3/Date/15.9.4.3.js:47] (this=0x2db26051 <JS Global Object>#1#)

==== Details ================================================

[2]: /* anonymous */ [test/mozilla/data/ecma_3/Date/15.9.4.3.js:47] (this=0x2db26051 <JS Global Object>#1#) {
  // stack-allocated locals
  var .result = 0x2db08091 <undefined>
  // expression stack (top to bottom)
  [01] : 0x2db26051 <JS Global Object>#1#
--------- s o u r c e   c o d e ---------
/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */?/* ***** BEGIN LICENSE BLOCK *****? * Version: MPL 1.1/GPL 2.0/LGPL 2.1? *? * The contents of this file are subject to the Mozilla Public License Version? * 1.1 (the "License"); you may not use this file except in compli...

-----------------------------------------
}

==== Key         ============================================

 #0# 0x2db25fb1: 0x2db25fb1 <JS Object>
 #1# 0x2db26051: 0x2db26051 <JS Global Object>
=====================

Aborted</pre>

**Comment by palfia** [comment]
I've bisected the problem to the commit:
a98cc600 Replaced the --limit-inling flag by three separate flags and bumped hard limits.

**Comment by paul99** [comment]
Dusan, can you take a look at Akos commit here: https://github.com/paul99/v8m-rb/commit/ca8d3fcb2b0f4c024b48c7ff33dd11ab49ecd052

and see if you have a better suggestion than I came up with to keep the delay-slot usage as obvious and clear as possible.

**Comment by dusmil** [comment]
I propose following solution to code size assertions that is much cleaner, and it is very similar to what Paul proposed earlier.

Insted of code in DoCmpT (lithium-codegen-mips.cc):

  Label done;
  __ Branch(USE_DELAY_SLOT, &done, condition, v0, Operand(zero_reg));
  __ LoadRoot(ToRegister(instr->result()), Heap::kTrueValueRootIndex);
  __ LoadRoot(ToRegister(instr->result()), Heap::kFalseValueRootIndex);
  ASSERT_EQ(3, masm()->InstructionsGeneratedSince(&done));

it should be:

  Label done, check;
  __ Branch(USE_DELAY_SLOT, &done, condition, v0, Operand(zero_reg));
  __ bind(&check);
  __ LoadRoot(ToRegister(instr->result()), Heap::kTrueValueRootIndex);
  __ LoadRoot(ToRegister(instr->result()), Heap::kFalseValueRootIndex);
  ASSERT_EQ(2, masm()->InstructionsGeneratedSince(&check));

Also on other spot in EmitIntegerMathAbs (lithoum-codegen-mips.cc) to deal with similar assertion:

  Label done;
  __ Branch(USE_DELAY_SLOT, &done, ge, input, Operand(zero_reg));
  __ mov(result, input);
  ASSERT_EQ(2, masm()->InstructionsGeneratedSince(&done));

I propose assertion removal, because what this assert is checking, if we know "mov" will be always one instruction which is in delay slot.

**Comment by paul99** [comment]
There is also this failing test:
ecma/TypeConversion/9.2.js

full command:
/opt/paul/v8/out/mipsel.debug/d8 --stress-opt --always-opt --nobreak-on-abort --nodead-code-elimination --enable-slow-asserts --debug-code --verify-heap --expose-gc /opt/paul/v8/test/mozilla/mozilla-shell-emulation.js --es5_readonly /opt/paul/v8/test/mozilla/data/shell.js /opt/paul/v8/test/mozilla/data/ecma/shell.js /opt/paul/v8/test/mozilla/data/ecma/TypeConversion/shell.js /opt/paul/v8/test/mozilla/data/ecma/TypeConversion/9.2.js --test

I did not get a chance to re-test with your change.

I got the idea that it's possible that the problem was not JUST the ASSERT fail, but the fact that we switch to long branch mode, and it does not look to me like long branches handle delay slot instructions properly.

If so, any of these delay-slot using sequences could return the incorrect value, as well as having a possible ASSERTION fail.

I did verifu that the second routine uses at least some long branches, but I did not get further with debug. 

Please take a look.

**Comment by paul99** [comment]
I moved the discussion of ecma/TypeConversion/9.2.js to https://github.com/paul99/v8m-rb/issues/28, as it seems unrelated.

I agree with what you wrote above, Dusan, and it seems like a clean way to fix.

However, in looking at the long-branch code, it also seems broken to me. Here is the first half of basic conditional branch:

```
void MacroAssembler::Branch(Label* L, Condition cond, Register rs,
                            const Operand& rt,
                            BranchDelaySlot bdslot) {
  if (L->is_bound()) {
    if (is_near(L)) {
      BranchShort(L, cond, rs, rt, bdslot);
    } else {
      Label skip;
      Condition neg_cond = NegateCondition(cond);
      BranchShort(&skip, neg_cond, rs, rt);
      Jr(L, bdslot);
      bind(&skip);
```

The problem that I see is the `bind(&skip)`, which is the target of the BranchShort() in the case where the _original_ branch is _not_ taken. If bdslot is used, then the `Jr()` does not emit a nop, and the skip label then points to the instruction in the delay slot, and it gets executed when it should not be.

It's fine when bdslot is `PROTECT`, and the `Jr` emits a nop (but humorously this doesn't matter anyway since its a nop).

The second half of Branch() routine has the same issue.

Looks to me like the BranchShort needs its jump target adjusted when using bdslot.

This is by observation only, and possibly I am mistaken. It would be most awesome to have a test-case for this, and be able to submit the test-case along with the fix!

**Comment by dusmil** [comment]
Thank you for checking this, it is good to be certain long branch is working properly.

If am not mistaken, instruction in branch delay slot is executed  no matter branch is taken or not.
You just described semantic of branch likely, and we do not need that.

**Comment by paul99** [comment]
Yes, you're right of course, not sure what I was thinking. The branch code is fine.

Please prepare a patch for your proposed fix above, and take a look to see if that sequence of checking code size appears anywhere else that also needs to be fixed.

**Comment by dusmil** [comment]
Patch for this is created and pushed to dm-dev..

**Comment by paul99** [comment]
This fix was landed today at google:

SHA  b224aeda4941b7f2ad6748bde00fc4ba816bc974
MIPS: Fix code size assertions for branch delay slots.
r 13848

Closing issue.
