### ISSUE TITLE
mips64 simulator data trace missing for dsll

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#162]
I noticed during some debugging that `doll` does not print its 'alu' value:

```
0x46f1a644  3c090000       lui     a5, 0x0                 0000000000000000
0x46f1a648  35290274       ori     a5, a5, 0x274           0000000000000274
0x46f1a64c  00094c38       dsll    a5, a5, 16               
0x46f1a650  35299358       ori     a5, a5, 0x9358          0000000002749358
```

I did not notice other instructions missing, but there may well be. When you find the missing spot for a `TraceRegWr()` you might see others missing as well.

Also, I noticed one branch instruction that does print something, but shouldn't -- and it interferes with the branch target printing (this from mips32):

```
0x54c0b468  02202825       mov     a1, s1                  f5272f0c
0x54c0b464  04110001       bgezal  zero_reg, 1 -> 0x54c0b46c   f5272f0c
0x54c0b46c  27ff0014       addiu   ra, ra, 20              54c0b480
```

Can you please take a look?

**Comment by ilijapavlovic** [comment]
The fix for `dsll` is already done, but for `bgezal` it seems little bit tricky. I see also that this instruction is not disassembled correctly.

**Comment by ilijapavlovic** [comment]
**dsll**
- In simulator:

```
  ...
  case DSLL:
    set_register(rd_reg, alu_out);
    TraceRegWr(alu_out);
    break;
  ...
```

**bgezal**
- Instruction "BGEZAL rs, offset" is 'removed from Release 6'.
- Instruction "BAL offset" is special case of BGZAL instruction where
  rs == zero_reg
- The problem was printing an instruction in delay slot of BAL/BGEZAL instruction.
  When printing details of the instruction in delay slot is finished, content of
  "trace_buf_" was not deleted, and that was the cause of printing an additional info
  in BAL/BGEZAL instruction.
- Solution for this was deleting "trace_buf_" content at the end of the
  "BranchDelayInstructionDecode()" function.

```
  ...
  void BranchDelayInstructionDecode(Instruction* instr) {
    ...
    InstructionDecode(instr);
    SNPrintF(trace_buf_, " ");
  }
  ...
```

**Comment by ilijapavlovic** [comment]
Fixed.
https://codereview.chromium.org/1245173002/

**Comment by ilijapavlovic** [comment]
Landed.
https://chromium.googlesource.com/v8/v8/+/a5f5f5801440e6b4d25be37441a65af2add9a7ef

**Comment by paul99** [comment]
This works great, thanks. Closing.
