### ISSUE TITLE
V8 built with Big Endian option when cross-compiled for mips

### ISSUE THREAD

**Issue by pmclee** [v8mips/v8mips#195]
I'm cross-compiling V8 for mipsel as part of the nodejs package. I was able to configure node to compile little endian and that works. But the little-endian option is not propagating down into the V8 build.

So I'm trying to cross compile V8 separately to see if there's some way to work around the node-V8 problem. But when I tried following the instructions at this page:

https://github.com/paul99/v8m-rb/wiki/Building-v8-for-MIPS-with-GYP 

But when I run "make dependencies" the command fails because `gclient` is not installed. I tried to apt-get gclient, but apt-get cannot find that package.

So how can I find out how to cross-compile V8 for mipsel? Are there environment variables I can set for the architecture? It seems like the support is there -- I'm just not able to pass in the right options. I'm pretty good with shell scripts and make, but I've never used gyp so I don't know how to read the files.

**Comment by paul99** [comment]
Hi Lee - I'm sorry that our wiki page you referenced is so out of date. I'll try to get that fixed soon, in the meantime, I will put info here to help. Unfortunately, I myself have not built node.js using v8, so I don't know what issues you will face there, but I do know that many others have done it successfully.

I suggest that you might want to start by building standalone v8 for mips, and checking that the `d8` debugging shell works on your target.

So yes, v8 build uses GYP, and GYP and `make dependencies` require `gclient`. `gclient` is part of the Google Chromium `depot_tools`, which are a variety of support scripts for working on Chromium family projects. 

This is how you get/install it: http://dev.chromium.org/developers/how-tos/install-depot-tools

These are all python scripts, and I think you must have python 2.7 installed on your build machine to use these.

Here are two links that describe getting & building v8 standalone. There may be some useful background info there: 

https://chromium.googlesource.com/v8/v8/+/master/docs/using_git.md
https://chromium.googlesource.com/v8/v8/+/master/docs/building_with_gyp.md

For your node build, you will want to use the release branch that they specify, I think that is 4.5. As described in the Google wiki pages above, the release branches are kept in git in a slightly non-standard way, so you should use the depot_tools `fetch` command to get your v8 checkout, so that you get the `branch-heads` pulled into your repo. (The `fetch` command adds the correct additional 'refs' needed to your `.git/config` file.)

This page documents how to cross-compile big-endian MIPS v8: https://github.com/paul99/v8m-rb/wiki/Building-v8-for-BE-with-QEMU

There is extra complication here to build v8 with startup snapshot. See this page for a brief description of what the snapshot is, and why you would care: https://wiki.qt.io/V8Snapshot  Basically, it makes v8 start up faster, which will be important for node. But you can build v8 without a snapshot, by adding `snapshot=off` to the make command line. You might do this first, to be sure you can get it working, then add qemu to build the snapshot image.

**Comment by pmclee** [comment]
Paul, Thanks for the reply. I think I'm missing some secret sauce for configuring gclient. I was able to install the depot tools OK. Then I tried to fetch V8. The results are almost comical. I've copied & edited & pasted below:

```
$ gclient fetch v8
You need to run gclient sync at least once to use 'recurse'.
$ gclient sync
Error: client not configured; see 'gclient config'
$ gclient config
Usage: gclient.py config [options] [url] [safesync url]
gclient.py: error: Inconsistent arguments. Use either --spec or one or 2 args
$ gclient --help config
Usage: gclient.py config [options] [url] [safesync url]
This specifies the configuration for further commands. ...
Options:
  --spec=SPEC           create a gclient file containing the provided string.
                        Due to Cygwin/Python brokenness, it can't contain any
                        newlines.
$ gclient config --spec=HELLO
  File "<string>", line 1, in <module>
NameError: name 'HELLO' is not defined
```

Derp. I didn't really expect HELLO to be a valid SPEC, but there wasn't much to go on here. I have no idea what URL it could possibly be asking for, nor have I been given any clue what a SPEC is.

Do you have any idea what would make gclient happy here?

**Comment by paul99** [comment]
Lee, the problem is the first line, you ran `gclient fetch v8`, it should be just `fetch v8`. 

`fetch` itself sets up the proper gclient config, so it calls 'gclient' maybe that is what the 'recurse' message referred to. Sorry the error messages are not human-readable :)

I just ran this on a Fedora[1]  machine I've never used before, and it does work without any additional config steps, but it pulls about a GB of data, so it may take a while:

```
$ fetch v8
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "managed": False,
    "name": "v8",
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
  },
]
'
Running: gclient sync --with_branch_heads
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28.4M  100 28.4M    0     0  3299k      0  0:00:08  0:00:08 --:--:-- 3538k
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all

$ du -sh v8
990M    v8
```

[1] I normally use ubuntu 14.04 as my cross-build machine.

**Comment by pmclee** [comment]
Thanks for the reply, Paul! I'm currently re-trying by building the newer nodejs 4.x source base. It looks like everything is building little-endian correctly, but now I've got other issues to solve. So I'm putting the separate V8 build on hold for the moment.
