### ISSUE TITLE
debug regress-undefined-nan & nan3

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#206]
With commit 1195b0e2 [turbofan] Initial support for keyed access to fast JSArrays. (https://codereview.chromium.org/1418213010) two tests are failing on mips32 & mips64 r2 simulators.

You can see the BB failures https://v8.mips.com/bbv8/builders/Sim%20-%20Debug%20-%20edge/builds/8995 & https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge/builds/5431  (since the BB was down for a long time today, there is a gap in tested commits, and this failed in the middle of that gap. I did bisect it to the commit above that causes the failure.

This fails only in _optdebug_ mode, and only on _turbofan_.

Per the buildbots this does not fail on r6 (I confirmed that), and does not fail on target hardware (I did not confirm, and I am suspicious of this. I would test this on mips32r2 hw as first step.

**Comment by lialan** [comment]
Was able to reproduce it in debug mode, and the reason it was failing only on debug/optdebug mode is that it hits an assertion in verify phase, which is only turned on for debug modes. Inside the test case, the function "loader" is called 3 times, as follows:

```
 loader(doubles, fixed_double_elements, 0);
 loader(doubles, fixed_double_elements, 0);
 %OptimizeFunctionOnNextCall(loader);
 loader(doubles, fixed_double_elements, 0);
```

It hits an assert while trying to verify the array's elements validness. And if you trace the code you will see it is the third "FixedDoubleArray::verify" function that caught the problem, which coincide with the    

```
%OptimizeFunctionOnNextCall(loader);
```

(edit: this paragraph is wrong) a valid value of the array element should be 0x3fe0000000000000 (since it is 3 identical function calls), however we are seeing: 0xfff7fffffff7ffff.

The next step would be to find the memory location of the value and monitor it to find the trespassing instruction which accidentally overwrites it.

**Comment by lialan** [comment]
The issue happens when V8 enables TurboFan function

```
JSNativeContextSpecialization::ReduceElementAccess
```

on a fixed double array access. My understanding of its reason is that "reduced" element access bypasses the canonicalization of the hole values in a double array, whereas in crankshaft function

```
void LCodeGen::DoStoreKeyedFixedDoubleArray(LStoreKeyed* insert)
```

we have canonicalization for such keyed access if the element type is float/double.

In TF, it seems there isn't any canonicalization operations yet. TF uses a cached hole value node throughout the building of graph, and assumes all holes are to be the same value.

**Comment by lialan** [comment]
The easy, immediate solution to this, is to bail out if we want to reduce double element arrays.

However that does not fix everything. A proper way to fix this would be: check why we identify the holey array to be a FAST_DOUBLE_ELEMENTS kind, and, identify it as HOLEY type. Perhaps before doing ReduceElementAccess, we should have an iteration of canonicalization of the array elements if the underlying element type is double.

**Comment by paul99** [comment]
This was described in the slack #nan channel, but the hardware bots fail on mjsunit/regress/regress-2596 only in --turbo mode, after the above mentioned CL.

**Comment by kisg** [comment]
Balázs fixed the issue with https://codereview.chromium.org/1507363002/
