### ISSUE TITLE
investigate: g++ note: variable tracking size limit exceeded ...

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#213]
I've noticed the following line of my target builds giving this error/warning/note. 

It does not seem to be a real warning, since we have `-Wall, -Werror`. I'm wondering if this is an issue that we should report to the compiler team?

I've checked this only on 2015.01-7/bin/mips-mti-linux-gnu-g++. Can you check if clang is OK, and since this is not arch-specific file, we could try some gcc's for arm or x86.

Ivica, maybe you can assign this to someone who has a few spare cycles. It's not urgent.

(scroll sideways below to see the errors) 

   /u/v8/4-gv8/v8/out$ /mips/proj/build-compiler/Codescape-SDK/CentOS/x86_64/MTI/Linux-gnu/2015.01-7/bin/mips-mti-linux-gnu-g++ '-DCR_CLANG_REVISION=247874-1' '-DV8_TARGET_ARCH_MIPS' '-DCAN_USE_FPU_INSTRUCTIONS' '-D__mips_hard_float=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_I18N_SUPPORT' '-DV8_USE_EXTERNAL_STARTUP_DATA' '-D_MIPS_ARCH_MIPS32R2' '-DFPU_MODE_FP32' '-DENABLE_DISASSEMBLER' '-DV8_ENABLE_CHECKS' '-DOBJECT_PRINT' '-DVERIFY_HEAP' '-DDEBUG' '-DTRACE_MAPS' '-D_GLIBCXX_DEBUG=1' '-DENABLE_HANDLE_ZAPPING' -I../. -I../include  -Wall -Werror -Wno-unused-parameter -Wno-long-long -pthread -pedantic -Wno-missing-field-initializers -EL -Wno-error=array-bounds -mhard-float -mips32r2 -Wa,-mips32r2 -mfp32 -EL -Wno-error=array-bounds -mhard-float -mips32r2 -Wa,-mips32r2 -mfp32 -g -Woverloaded-virtual -Woverloaded-virtual -fdata-sections -ffunction-sections -O3 -fdata-sections -ffunction-sections -O3 -Wnon-virtual-dtor -fno-exceptions -fno-rtti -std=gnu++0x -MMD -MF /u/v8/4-gv8/v8/out/mipsel.optdebug/.deps//u/v8/4-gv8/v8/out/mipsel.optdebug/obj.target/cctest/test/cctest/test-asm-validator.o.d.raw   -c -o /u/v8/4-gv8/v8/out/mipsel.optdebug/obj.target/cctest/test/cctest/test-asm-validator.o ../test/cctest/test-asm-validator.cc
    ../test/cctest/test-asm-validator.cc: In function ‘void {anonymous}::CheckStdlibShortcuts(v8::internal::Zone_, v8::internal::ZoneVectorv8::internal::ExpressionTypeEntry&, size_t&, int&, v8::internal::TypeCache&)’:
    ../test/cctest/test-asm-validator.cc:397:6: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
     void CheckStdlibShortcuts(Zone_ zone, ZoneVector<ExpressionTypeEntry>& types,
          ^

**Comment by ibogosavljevic** [comment]
var-tracking-assignments is a feature of GCC used to track variable assignments during optimizations. It is enabled if both DEBUG symbols and optimizations are enabled simultaneously. Default version on GCC 4.8.3 is 50000000 (I saw this from GCC source code, PARAM_MAX_VARTRACK_SIZE), I didn't find a way to make gcc executable printout the default value.

If this limit were to be higher than 50000000, this could possibly slow down the compilation and require more memory to compile. The warning itself doesn't have any effect on the execution of the program, but it does have effect when we try debug the program.

We can increase the limit by specifying  --param=max-vartrack-size=N on the command line. If I compile with  --param=max-vartrack-size=60000000, the warning disappears.

**Comment by paul99** [comment]
@ibogosavljevic, thanks for the explanation, I was unaware of this feature. 

> but it does have effect when we try debug the program.

Can you explain what this effect is? I assume you mean problems when using gdb, but please clarify.

My concern was the warning during opt debug builds, and wondering if there was a scenario where that would turn into a build error.

We seem to run into this only on a single file, so if we increase the limit, would that affect compilation time of all files, or only the one file that goes above the current limit? It the latter is the case, we might add this to MIPS-specific CFLAGS for gcc builds. (would have to make sure we do not break clang target-builds)

If this has general build-time problem, then maybe we should realize _most_ builds are not for gcc, they are for buildbots or running tests locally, and we could add a local patch for building for debug with gdb. (I do not prefer this, it seems kind of lame, but I'd hate to penalize buildbots if this were to significantly affect build time -- hoping & guessing that it does not)

**Comment by ibogosavljevic** [comment]
Additional info from today's investigation:

The message we are seeing is not a warning, but a note. After the file name and line number, we see the type of message, this message is a note from the compiler. This is why the compilation passes even if the line is present. The other types of outputs are error and warning.

According to official documentation from GCC:
`-fvar-tracking-assignments: Annotate assignments to user variables early in the compilation and attempt to carry the annotations over throughout the compilation all the way to the end, in an attempt to improve debug information while optimizing. Use of -gdwarf-4 is recommended along with it.
It can be enabled even if var-tracking is disabled, in which case annotations are created and maintained, but discarded at the end. By default, this flag is enabled together with -fvar-tracking, except when selective scheduling is enabled.`
From the internet as well: `On note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without`: `This is just a note from the compiler that the debug info for the particular function will have lower quality, because your code of function is too large/complex so variable tracking reached limit of hash table slots.`

From the above said, I would be surprised if this warning would create a compiler failure somewhere in the future.

Similar warning appeared on Chromium earlier, and they fixed by refactoring the code so it disappears (https://codereview.chromium.org/1164893003). I like this path and maybe we should take it, but read on...

Building using GCC (export GYP_DEFINES="clang=0") for mipsel.optdebut x86 simulator doesn't give us this error. Even if we compile with very low number for assignment tracking (--param=max-vartrack-size=200000 vs --param=max-vartrack-size=50000000) we don't get the warning. This could indicate some problem with the compiler or maybe with the library: why would GCC for MIPSEL generate 200 times more assignments than X86. It's a riddle to me, and definitely requires some more investigation. I tried the newest version 2015-11 of MIPS GCC toolchain, but the problem appears there as well

Another option is to completely shutdown variable assignment tracking using -fno-var-tracking-assignments option. This speeds up compiling, on my system compiling test-asm-validator.cc took 30 s without this option and 13 s with this option. And good thing is that we don't get any warning. The bad thing  is that this option is not supported by CLANG, so we need to make sure this compiles both ways.

I couldn't find any option to suppress this message on GCC. I expected that -Wno-var-tracking-assignments disables the warning, but that's not the case

_Summary_: I will try to refactor this test so it gives no warning. I will also try to figure out why this function has so many assignment, which may cause that we signal bugs to the compiler team.

**Comment by ibogosavljevic** [comment]
Compilatio performance on mips32r2, using cross toolchain:

without variable-assignment-tracking
  TOUCH /home/ivica/src/o_main3/v8/out/mipsel.optdebug/obj.target/build/All.stamp
make[1]: Leaving directory `/home/ivica/src/o_main3/v8/out'

real    10m47.670s
user    64m38.190s
sys 2m10.036s

with variable-assignment-tracking
  TOUCH /home/ivica/src/o_main3/v8/out/mipsel.optdebug/obj.target/build/All.stamp
make[1]: Leaving directory `/home/ivica/src/o_main3/v8/out'

real    11m38.335s
user    69m35.215s
sys 2m12.175s

**Comment by ibogosavljevic** [comment]
PTAL: https://codereview.chromium.org/1491583002

**Comment by paul99** [comment]
I'm sure it is fine. But please use the CQ Dry Run, so I can see the results from Google bots on all arch's. (On the 'Trybot Results' line at the bottom of the blue box with your patchset in it.)

(Note you can also explicitly use TryBots to test even more variations -- though I don't think that necessary here. If you use that, scroll down the v8 section as the first few sections are Chromium related.)

**Comment by ibogosavljevic** [comment]
Did dry run and it passed. But we need to have someone from the maintainers to do LGTM. Do you know who should we add?

**Comment by ibogosavljevic** [comment]
Patch landed, closing
