### ISSUE TITLE
Remove global clang-format-off from test-assembler-mips[64].cc

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#223]
@ibogosavljevic : could you ask one of the guys to remove this clang-format off line that Jochen is mentioning here? https://codereview.chromium.org/1047213002/

It was done a long time ago, but we should treat his comment as a porting request and fix here, and other places in mips port that do this,  if any. (likely test-assem-mips64). Please cc him on fix with @kilvadyb or @palfia for review.

This may make a mess of some formatted parts of this file.  Lots of that was done by @djordje.pesic so maybe he should review also.

Confirmed that this is in test-assembler-mips64.cc also and should be removed. Note that if there are particular (smallish) places/scopes in the code that we really want to preserve formatting, that's fine.

Also, no need to remove the other 'clang-format off' usages from elsewhere in mips port, as they seem to be in all arch's (full-codegen-*, etc)

(Pri-1 since this was requested by Google last week (slack porting requests). It should be easy, lets just get it done.)

**Comment by ibogosavljevic** [comment]
Paul fixed this and landed the CL. Please note that he just removed clang-format off without making changes to the formatting of the files. This makes sure the files become more and more CLANG conformant as time goes by without too much changes to files themselves (we don't want to make files CLANG compliant  for the time being as we expect a lot of merging and changes due to R6 implementation, we should create a tracking issue for this )

Original CL:
ac33eaba10644a9f29095f2a56b98914bbbda047

MIPS: Remove clang-format-off from assembler tests.

Per request in https://codereview.chromium.org/1047213002/

These files will continue to have a lot of churn in next two months
as we finish support for MIPS r6 instruction set. When things settle
down, we will do a clang-format --full to clean them up. For now,
we'd prefer to be able to do easy diffs, and will do incremental
re-formats as we make changes.

BUG=

Review URL: https://codereview.chromium.org/1546973003

Cr-Commit-Position: refs/heads/master@{#33038}
