### ISSUE TITLE
Are there some methods to improve the performance of v8 on loongson

### ISSUE THREAD

**Issue by loongson817** [v8mips/v8mips#24]
Hi
  Last two months, I tried to do something to improve the performance of v8 on loongson3a(mips64), but failed.
Like:
1. profile thread decide which function is small function in order to use crankshaft OPT compile. 
       static const int kMaxSizeEarlyOpt = 5_FullCodeGenerator::kBackEdgeDistanceUnit(5_142->5*250)
2. I want to know if or not so many stack check will slow the program.
3. I try to find some instructions to replace nop. (jal , jalr, loop-branch)
   
   They did not work well at all. So, are there some ways I can do to improve the proformance? I need some points, suggestions. Any method，I will try.  Thanks.

**Comment by paul99** [comment]
Sorry for the late response to your question. Unfortunately there is no simple answer. Optimization on v8 is hard. We've taken most of the low-hanging fruit. There was an optimization patch 6 months back or so that filled a lot of delay slots, and that helped, about 5% or so. At this point, 5% is HUGE, and a great benefit.

Also guessing that optimization would very likely not be Loongson specific, but may benefit all mips platforms. Which is good as well.

Another issue is that the v8 benchmarks have a 1% to 1.5% variation, so if your improvement is less, you have a hard time proving it helped. We have a test-runner that runs the benchmark 20 times and averages the results. That helps.

It might be good to do some micro-benchmarking, rather than looking for top level stuff.

One idea is to use the mips simulator running on x86, run the individual v8 or sunspider benchmark tests one at a time, with the --trace-sim flag on, and you will generate HUGE (multi-gigabyte) log files tracing every mips instruction executed. You could write analysis scripts that look for common loops, then go back to where these are generated, and try to optimize them.

I think that v8 now supports the 'perf' tools in the linux kernel. I have not set this up, and it is somewhat tedious to get it all working, but this is another really good tool to look for hotspots.

Good luck, and let us know what you find.

**Comment by sosohu** [comment]
Recently, I also do this for the loongson. So,how to run mips64 on the loongson3a?  

I tried to compile the v8 with mips64 on the loongson3a in release mode. And the result is the compile is ok, but when I run the v8's benchmark , such errors occurred:
Richards: Error: Error during execution: queueCount = 149, holdCount = 59.
DeltaBlue: ReferenceError: alert is not defined
....
Is not I also need to change some files to support mips64?   ( I succeeded in mips3 way)

**Comment by loongson817** [comment]
Hi:

  Maybe you need rebuild gcc, Changs some code in mips.c in gcc source  code.
since line 9571; 
 if (GP_REG_P (regno))
    return (((regno - GP_REG_FIRST) & 1) == 0 || size <= UNITS_PER_WORD);

/_lanxiaoming add for loongson3a and 3b not to use odd number register!_/

  if (FP_REG_P (regno) &&  ((regno - FP_REG_FIRST) % 2 == 1) && (size == 4))
    return false;

  if (FP_REG_P (regno)
      && (((regno - FP_REG_FIRST) % MAX_FPRS_PER_FMT) == 0
      || (MIN_FPRS_PER_FMT == 1 && size <= UNITS_PER_FPREG)))

If this don't work, we can discuss more details.

**Comment by dusmil** [comment]
Hi guys,

Yes this is a problem,  the n64 ABI implies 32  64-bit FPU registers( FR=1 mode), and v8 does not support this, only 16 pairs of 32bit FPU registers (FR=0 mode).

Further more,
I also assume you compiled v8 for n64 ABI, and this requires additional changes in v8 internals in order to make it work. The V8 can call C++ run-time routines from generated native code, therefore proper native code conformant to n64 ABI spec must be generated. The changes have to be done in CEntryStub, and in macro-assembler function "PrepareCallCFunction" how arguments are passed to C++ functions. There is more, after each call, code have to be changed to expect returned result in proper register. Also keep in mind there is different frame alignment constraints. Argument passed on stack are placed on 64-bit boundaries. Probably, there are more differences that needs to be addressed. 

It should be easier to do changes for n32 ABI, rather than for n64, but still may happen it won't be straight forward.

**Comment by sosohu** [comment]
Hi loongson817.
I did it as you say , but unfortunately, the rebuild gcc on loongson3a is so  difficult. Until now, I have not succeeded to rebuid gcc...
In addition, I want to know whether you are the graduate from USTC(0711) , named Lan XM?

**Comment by paul99** [comment]
We now have full support for mips64el, which runs fine on the Loongson 3A, and much of that code was contributed by Yuyin at Loongson. Closing this.
