### ISSUE TITLE
Use MADD/MSUB instruction in instruction selection

### ISSUE THREAD

**Issue by lialan** [v8mips/v8mips#249]
We can combine multiply and add/subtract to a single MADD/MSUB instruction.

For floating point operations, on R2 there are MADD.Fmt/MSUB.Fmt instructions. On R6 there are MADDF/MSUBF instructions.

**Comment by lialan** [comment]
PTAL:
https://codereview.chromium.org/1657303002/

**Comment by ibogosavljevic** [comment]
There will be problems with MADDF and MSUBF on R6. These two instructions use internally 80bit precision when working on 64bit double values. As a consequence, we can expect to see some tests failure because of this.

Earlier, we had issue that some tests were failing because the test results were obtained using compiler generated MADDF whereas v8 was generating separate MUL/ADD sequence. Please see #208. 

Paul was against that we use MADDF/MSUBF in v8. I don't remember exact reasoning behind this, but he wanted that we disable usage of MADDF/MSUBD in the compiler code as well (this doesn't work at the moment with the compiler we are using, there is a bug report for this)

**Comment by ibogosavljevic** [comment]
R2 shouldn't have this problem, but please run all tests to confirm this

**Comment by lialan** [comment]
The submitted CL only contains R2 change. R2 tests all pass.

I got some issue when implementing MaDDF. I was thinking a solution. But since you mentioned that incompatibility, I will take a look at the MADDF issue, thanks.

**Comment by kilvadyb** [comment]
#379 covers and solves this issue.
