### ISSUE TITLE
Bughunting: mjsunit/wasm/module-memory

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#268]

**Comment by ibogosavljevic** [comment]
https://v8.mips.com/bbv8/builders/Target%20-%20edge/builds/6629/steps/Check/logs/module-memory

**Comment by ibogosavljevic** [comment]
Issue fails because WASM -> mips compilation generates unaligned pointer and this fails on some machine.
WASM operators carry with them Align attribute, but this is not pushed down to MIPS code, so we don;t know what kind of access to generate (aligned or non-aligned).
The idea is to introduce two new turbofan operators UnalignedLoad and UnalignedStore for this kind of memory access, and generate MIPS code that has the ability to access this kind of code.
CL is available here, please take a look:
https://codereview.chromium.org/1779713009

**Comment by palfia** [comment]
The CL looks good, let's wait for Ben's comments. Also, it touches other archs, so please test this CL on all archs thoroughly.

**Comment by ibogosavljevic** [comment]
The above CL didn't land, because a different approach was decided: Now, instead of UnalignedLoad and UnalignedStore turbofan operators, we simulate unaligned access in wasm-compiler.cc using Load/Shift/Or and StoreByte/Shift/And.

So, we implemented:
1) CL implements unaligned access instruction for MIPS32 and MIPS64 (landed and closed)
https://codereview.chromium.org/1902743002
2) CL implements architecture-independent part: simulate unaligned access in wasm-compiler.cc using Load/Shift/Or and StoreByte/Shift/And: https://codereview.chromium.org/1928513002/ (LGTM, being tested currently, but should land soon). After this, the failures will disappear.
3) CL implements UnalignedLoad and UnalignedStore reductors: Since MIPS supports instruction for UnalignedLoad and UnalignedStore, another CL is being on review that detects combination of these turbofan operators, and replaces them with LWL/LWR or SWL/SWR sequences. (on code review)

To be implemented:
4) Tests to verify that unaligned emulation  in wasm-compiler.cc is not being changed so it is not recognized and reduced. This is now a part of separate bug #317

**Comment by ibogosavljevic** [comment]
After some deliberation, we decided to implement UnalignedLoad and UnalignedStore operators. This means that we don't need MIPS reductors anymore.

The CL is here https://codereview.chromium.org/2182433002/. It has landed, all the tests are now passing, so i am closing this issue.
