### ISSUE TITLE
WASM: Fix linear-memory access related test failures on big-endian.

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#276]

**Comment by palfia** [comment]
This issue will be addressed in #268.

**Comment by ibogosavljevic** [comment]
This issue is not related to #268. #268 deals with unaligned access in WASM and it exists on both little endian and big endian. This issue exists on big endian only.

I am in the process of trying of following approach: we will keep data in memory in little-endian order, even on big endian. To achieve this, we do the following: in wasm-compiler.cc, before each store we convert data to little-endian. Also after each load, we convert data to big-endian. Let us see how will this approach work.

**Comment by ibogosavljevic** [comment]
https://codereview.chromium.org/2034093002/ fixed failures on WASM on MIPS64 BE. MIPS32BE still experiences some failures with int64, the reason int64 to int32 lowering that doesn't respect BE memory layout. A subsequent patch should fix this

**Comment by ibogosavljevic** [comment]
All tests are now passing from cctest/test-run-wasm\* on big-endian, so this issue will be closed. The uploaded solution is not the optimal one, since we use turbofan operators to simulare byteswapping withing word.

Currently, a new CL https://codereview.chromium.org/2045943002/ is on review. This introduces a new turbofan operators that correspond to MIPS instructions to byte swapping. This will allow a much faster implementation. This is a part of #345
