### ISSUE TITLE
Bughunting: clang target failures

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#279]
https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20clang/builds/1137

**Comment by ibogosavljevic** [comment]
Failures that are specific to CLANG are: unittests/AstDecoderTest.Float32Const and unittests/AstDecoderTest.Float64Const.

I couldn't reproduce the failure in my environment.  From the logs I see that the failure is related to "CRASH: BUS ERROR maybe alignment problem". The patch which fixes the problem with unaligned access in WASM is under review as part of bug #268.

Let's put this issue on hold until it lands, and if this fixes the issue, super, otherwise, we'll reopen the issue and setup an identical environment as on buildbots.

**Comment by ibogosavljevic** [comment]
Not solved by patches from #268 :(

**Comment by ilijapavlovic** [comment]
The problem is not reproduced also on big endian board. mips.release and mipsel.release are executed under qemu user and in these cases the problem is not reproduced.

**Comment by ibogosavljevic** [comment]
The issue was fixed here: https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20clang/builds/1306 ans hasn't been reproducing ever since. Closing...
