### ISSUE TITLE
Port new CL to MIPS: https://codereview.chromium.org/1901573003/

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#297]
Port new CL to MIPS: https://codereview.chromium.org/1901573003/

**Comment by ilijapavlovic** [comment]
CL ready for review: https://codereview.chromium.org/1903173002/
Should be also tested for mips64.r2, mipsel.r2, mips64el.r2

**Comment by ilijapavlovic** [comment]
CL  https://codereview.chromium.org/1903173002/ is tested for mipsel and mips64el.
Based on previous CL, one new CL is created by Yang: https://codereview.chromium.org/1902393004
Committed as b4697727e946e8d96d5345a4db7ff72842d60466

**Comment by ilijapavlovic** [comment]
New CL uploaded because of problem with executing specific test cases on simulator.
https://codereview.chromium.org/1904033003/

Failed test cases on simulator for mips64.release:
- test/mjsunit/harmony/regexp-property-blocks.js
- test/mjsunit/regexp-sort.js
- test/mjsunit/regress/regress-sliced-external-cons-regexp.js
- test/mjsunit/string-slices-regexp.js
- test/mjsunit/harmony/unicode-regexp-unanchored-advance.js
