### ISSUE TITLE
Bughunting: Flaky test/mjsunit/regress/regress-crbug-514081.js and regress-crbug-644631.js under clang

### ISSUE THREAD

**Issue by marijantic** [v8mips/v8mips#405]
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang/builds/1672/steps/Check%20%28flakes%29/logs/regress-crbug-514081
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang/builds/1672/steps/Check%20%28flakes%29/logs/regress-crbug-644631

**Comment by marijantic** [comment]
Could not reproduce the issue on XLP board. Tried running 100 times with and without alignment fix sysmips(MIPS_FIXADE, 0);

**Comment by marijantic** [comment]
First occurrence of the flaky test: https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang/builds/1608

**Comment by kwan0xfff** [comment]
I've been running regress-crbug-514081 on an ER Pro-8 with a set of other regression tests, using -j 2.  In some cases, the amount of memory used exceeded 2 GB. At that point, the OOM killer would be invoked, crashing the test.  I later added an auxiliary swapfile, increasing overall swap space from 2 GB to 3 GB.  Over 10+ iterations of the test, I got max swap usages from 1.67 to 2.37 GB; none of these cases were killed.

High-level runtest is something like:
     python tools/run-tests.py \
        -j 2 --no-presubmit --verbose \
        --mode release --arch mips64el --outdir out \
        --random-seed -1 \
        --json-test-results /tmp/limited.json --timeout=600 \
        mjsunit/regress/regress-crbug-514081 mjsunit/regress/regress-crbug-630559
I had several runs where I added 16 regress-crbug tests in addition to 514081 itself.

Low-level command:
  /bbv8-slaves/erpro8-brd095el/build/slave/fake_slave/build/v8/out/mips64el.release/d8 --test --random-seed=-1 --ignition-staging --nohard-abort --nodead-code-elimination --nofold-constants /bbv8-slaves/erpro8-brd095el/build/slave/fake_slave/build/v8/test/mjsunit/mjsunit.js /bbv8-slaves/erpro8-brd095el/build/slave/fake_slave/build/v8/test/mjsunit/regress/regress-crbug-514081.js

Turns out that running 2 simultaneous copies of the low-level command takes variable amounts of swap space.  I got 1.66 GB and 2.37 GB.  Just running a single copy uses 0.26 GB.  (Why such a disparity between 1 and 2 copies?)

**Comment by kwan0xfff** [comment]
Swap spaces on affected machines was increased today (11/15 about 3pm PST) to "ridiculously large".  Possibly the crashes of "regress-crbug-514081.js" will disappear.

**Comment by mkaric** [comment]
This is most probably related to #360 and #366 as well. These have been failing occasionally for a long time now. Also there seems to be more tests behaving similarly (regress-655573...). Variable amounts of swap space used is certainly worth investigating.

**Comment by marijantic** [comment]
The test 514081 tries to allocate a 2GB Array Buffer, and this is the reason for OOM failure. Similar issue reported by NodeJS team, for x86 https://github.com/nodejs/node/issues/6340 and PPC https://github.com/nodejs/node/issues/8750

**Comment by marijantic** [comment]
NodeJS team fixed this by forcing only one instance of the test to be executed, so we will set NO_VARIANTS for it also.
