### ISSUE TITLE
Bughunting: Improper use of odd floating point register on MIPS32R6

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#430]
Currently, on MIPS32R6 we use an odd floating point register F19 (defined as kDoubleCompareReg) to hold the result of the comparation with CMP instruction that we use afterword in BC1EQZ. In case the hardware switches to FRE mode, this causes writes to odd registers to be treated as writes to upper part of even register, which then causes corruption of an even register.

To reproduce this easily, we would need to force FRE mode in hardware. There is a system call to do this:
prctl(PR_SET_FP_MODE, PR_FP_MODE_FRE). We need to execute the tests in FRE mode and check if everything works correctly.

**Comment by simicicd** [comment]
In order to turn on FRE mode we must use prctl system call in this format:
`prctl(PR_SET_FP_MODE, PR_FP_MODE_FRE | PR_FP_MODE_FR);`

Not all qemu branches have support for this mode, but i6400-mips64r6-PRIP4 branch from qemu-prpl repository (https://github.com/prplfoundation/qemu) has it.

When the value for kDoubleCompareReg register is changed from f19 to f26 (from odd numbered to even numbered fp register), a lot of test fail with bad_alloc error. This crash happens inside insert() method from unordered_map class from standard library. std::__detail::_Prime_rehash_policy methods are using odd floating point registers, so only way to fix this types of errors is to use toolchain which has libraries built with -mno-odd-spreg option.

When the v8 is built for soft floating-point this is the results of running all of the tests on qemu-prpl:
1. FRE=0 + kDoubleCompareReg=f19 :  562 tests failed
2. FRE=1 + kDoubleCompareReg=f19 :  739 tests failed
3. FRE=1 + kDoubleCompareReg=f26 :  556 tests failed

CL for this problem is uploaded here: https://codereview.chromium.org/2591063003/

**Comment by ibogosavljevic** [comment]
Testing FRE mode is a bit complicated, since all libraries needs to be compiled with -no-odd-spreg in order to support this. We used system call in the code to explicity enable FRE mode, otherwise we would need a complicated library arrangement in order to provoke FRE mode.

We tested using softfloat libraries in the Linux environment, since these should work fine with FRE. The fix simply disabled odd registers in the emitted code. Our observation is that the problem is fixed and this issue is closed.
