### ISSUE TITLE
Do we need to port "ARM: Small copy optimization. Copying 64bits at a time."?

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#44]
TODO: Check if the port of this commit can improve performance on MIPS: 

http://code.google.com/p/v8/source/detail?r=14254

**Comment by paul99** [comment]
This CopyFields is used in 2 places now, and their commit added a third. One of those places is for copying a JSObect header, which is 12 bytes. The other 2 are copying RegExp literals, which if my arithmetic is right, would be 36 bytes. So I believe payoff would be small.

There are two challenges to doing this on mips:
- Due to alignment issues of ldc1/sdc1, we will have to do alignment at runtime, since the code can be emitted once, and used for multiple different objects, with possibly different alignment. The runtime alignment check probably involves branching, and would likely overshadow any performance improvement we could gain.
- Currently our assembler emits two lwc1 for each ldc1 instruction. We'd have to add new assembler instructions to actually emit ldc1/sdc1.

I think this should be low priority, but it may be worth a trial run at some point.

**Comment by paul99** [comment]
My opinion is that due to the alignment issue (1st bullet in prev comment), this is unlikely to be worth doing. Closing. (If someone disagrees, please re-open)
