### ISSUE TITLE
Bughunting: Segmentation fault in ValueSerializerTestWithWasm.DecodeWasmModuleWithInvalidDataLength unittest

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#443]
Failure appears when V8 is compiled with Chromium, not on our buildbots

**Comment by simicicd** [comment]
This error can be reproduced only when unittest file (compiled for ARM or MIPS simulator) is directly executed (not by tools/run_tests.py script), so all tests are executed together. When the script is used, each test from ValueSerializerTestWithWasm test case is separately executed and the problem is masked. DecodeWasmModuleWithInvalidDataLength test fails only when it is executed after the DecodeWasmModuleWithInvalidCompiledAndWireData test from same test case.

DecodeWasmModuleWithInvalidCompiledAndWireData test generates scheduled exception which is not handled in current test, and that will produce Context::New(isolate()) from next test's constructor returns NULL, which then causes the DecodeWasmModuleWithInvalidDataLength test to fail. One solution is to add destructor to ValueSerializerTest test fixture class which will clear scheduled exceptions for current test from ValueSerializerTestWithWasm test case.

CL for this problem is uploaded here: https://codereview.chromium.org/2644083002

**Comment by ibogosavljevic** [comment]
Chrome team confirmed that the issue is resolved. Closing.
