### ISSUE TITLE
New feature: Explore compilation GN + CLANG + Debian buildroot + GOLD for MIPSEL

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#466]
v8 is in the process of migration from GYP to GN build system. We need to help support this. Currently the MIPS compiles with simulator. 

```
Here are the steps to compile v8 simulator using GN:
For MIPS32r2:  gn gen out.gn/mipsel_debug --args='is_debug=false target_cpu="x86" v8_target_cpu="mipsel" mips_arch_variant="r2"'
For MIPS64r2: gn gen out.gn/mips64el_debug --args='is_debug=false target_cpu="x64" v8_target_cpu="mips64el" mips_arch_variant="r2" '

This creates configuration and stores it in out.gn/mipsel_debug directory.

To compile:
ninja -C out.gn/mipsel_debug

To execute the tests:
tools/run-tests.py --outdir out.gn/mipsel_debug

Name of the directory can be anything instead of out.gn/mipsel.
```

We need to add support for the compilation on the target GN + CLANG + Debian buildroot + GOLD for MIPSEL

**Comment by sretenkovacevic** [comment]
Since in GN option --dynamic-linker is not supported, so loader can't be explicitly given to v8 I had to make a small patch that adds this functionality. This is workaround until we get good fix from chromium.

[LDSO_PATH_PATCH.zip](https://github.com/v8mips/v8mips/files/879290/LDSO_PATH_PATCH.zip)
After this patch is applied next command gives us wanted configuration:

```
gn gen out.gn/mipsel_debug_clang --args='is_debug=true
target_cpu="mipsel" v8_target_cpu="mipsel" mips_arch_variant="r2" 
is_clang=true target_os="linux" 
gcc_target_rpath="/home/ci20/sreten/Documents/v8/build/linux/debian_wheezy_mips-sysroot/lib/mipsel-linux-gnu:
/home/ci20/sreten/Documents/v8/build/linux/debian_wheezy_mips-sysroot/usr/lib/mipsel-linux-gnu:\$ORIGIN/."
ldso_path="/home/ci20/sreten/Documents/v8/build/linux/lib/mipsel-linux-gnu/ld-2.13.so"'
```
This is needed because on boards we have jessie sysroot, so we must specify path to wheezy libraries that we are using in runtime.

If you are using board with debian wheezy, this patch is not needed, and  gn command is much simpler (no ldso_path and gcc_target_rpath variables are needed):

```
gn gen out.gn/mipsel_debug_clang --args='is_debug=true
target_cpu="mipsel" v8_target_cpu="mipsel" mips_arch_variant="r2" 
is_clang=true target_os="linux"'
```

**Comment by ibogosavljevic** [comment]
This issue has been completed, closing. Related to location of dynamic linker and libraries, please see #473
