### ISSUE TITLE
New feature: Explore compilation GN + GCC + for MIPSEL and MIPS64EL

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#471]
v8 is in the process of migration from GYP to GN build system. We need to help support this. 

We need to add support for the compilation on the target GN + GCC + for MIPSEL and MIPS64EL

**Comment by sretenkovacevic** [comment]
Successfully compiled both MIPSEL and MIPS64EL using gcc.

To manage this it's necessary to do the following:

1. In bin folder of mips-mti-linux-gnu 2015.01-7 toolchain make BUILD.gn file with this content: 
[toolchain_definition.zip](https://github.com/v8mips/v8mips/files/905291/toolchain_definition.zip)

It's important to set additional flags (extra_ldflags and extra_cppflags). for both toolchain definitions because they actually make the difference.

2. Set appropriate GN arguments:
- If target is MIPSEL, run this gn command:
```
gn gen out.gn/mipsel_debug_gcc --args='is_debug=true target_cpu="mipsel" v8_target_cpu="mipsel" mips_arch_variant="r2" is_clang=false use_sysroot=false custom_toolchain="/home/rtrk/software/mips-mti-linux-gnu/2015.01-7/bin:mipsel"'
```
_mipsel_ after column in custom_toolchain argument states the name of the toolchain that is set in BUILD.gn file on given path.

- If target is MIPS64EL, run this gn command:

```
gn gen out.gn/mips64el_debug_gcc --args='is_debug=true target_cpu="mips64el" v8_target_cpu="mips64el" mips_arch_variant="r2" is_clang=false use_sysroot=false custom_toolchain="/home/rtrk/software/mips-mti-linux-gnu/2015.01-7/bin:mips64el" enable_nacl=false'
```
enable_nacl should be set to false because there is still no [Native Client](https://developer.chrome.com/native-client) support for mips64el build.

3. Export path to the toolchain bin folder to PATH environment variable. 

4. Run ``ninja -C out.gn/mipsel_debug_gcc/`` or ``ninja -C out.gn/mips64el_debug_gcc`` accordingly.

**Comment by ibogosavljevic** [comment]
Finished, issue closed
