### ISSUE TITLE
Optimization: Fix restartability issues

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#500]
According to MIPS instructions, certain instruction cannot be used in some combination of registers because of restartability issues. For example, instruction BGEZAL cannot use register 31 as source register.

Please go through the instruction manual, find instructions that have restartability issues and add checks in assembler-mips[64] in order to make sure these functions are never called with bad registers.

**Comment by ilijapavlovic** [comment]
Following restartability issues are identified:
- "_Branch-and-link Restartability_": GPR 31 must not be used for the source register `rs`. Affected instructions: `BGEZAL`, `B{LE,GE,GT,LT,EQ,NE}ZALC`, `BGEZALL`, `BLTZAL`, `BLTZALL`. This should be implemented.
- "_Jump-and-Link Restartability_": Register specifiers `rs` and `rd` must not be equal. Affected instructions: `JALR`, `JALR.HB`. This is already implemented.

For `JIALC` instruction, the register specifier may be set to the link register $31, because compact jumps do not have the restartability issues of jumps with delay slots.

**Comment by ilijapavlovic** [comment]
CL uploaded and ready for review:
https://chromium-review.googlesource.com/c/549362/

**Comment by ilijapavlovic** [comment]
CL landed:
https://chromium.googlesource.com/v8/v8/+/7a6d35e689746fffc9110ee28880da52319e12f2
