### ISSUE TITLE
Support for NaCL sandboxing in mips v8.

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#53]
To run JavaScript in a protected sandboxed environment for Arm, v8 can be compiled to run the arm simulator compiled for arm target. Changes were made to gyp files to support this.

We need similar changes for mips.

Dusan has compiled the v8/simulator and run it on MIPS target successfully, and ran the regression test suites. So this is an excellent proof of concept.

Note that https://github.com/paul99/v8m-rb/issues/11 describes some fairly severe performance problems in the MIPS v8 simulator, and these should get addressed if this will be used in a product.

**Comment by kisg** [comment]
As far as I know, NaCL does support JIT-ed code, and there is a proof of concept port of an older V8 Crankshaft version here:
http://naclports.googlecode.com/svn/trunk/src/experimental/v8/README

Did some things change in the NaCL world, that makes this impossible? 

I don't think that running V8 in simulator mode inside NaCL makes sense in a production environment if regular JIT mode can be supported. Of course, improving simulator performance makes sense from other perspectives.

It looks like  there are substantial changes required to V8, because the dynamic code has to be put in a separate address region. However, implementing these changes would bring us closer to W^X, meaning that executable code can sit in non-writable pages most of the time. I think we should consult with the Google V8 team before investing too much into this.

**Comment by kisg** [comment]
Not in scope for now.
