### ISSUE TITLE
New feature: Enable test-run-wasm-simd with MSA instructions

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#535]

**Comment by prudic** [comment]
On MIPS platforms which don't support SIMD, test-run-wasm-simd tests are disabled if they fail because simd lowering mechanism doesn't work properly yet.
When building  for MIPS architectures that does support SIMD (currently only r6), "mips_use_msa" flag has to be set to "true" to include MIPS_SIMD support in CpuFeatures class.
CL: https://chromium-review.googlesource.com/c/v8/v8/+/868430

**Comment by ibogosavljevic** [comment]
Closed
