### ISSUE TITLE
Bughunting: RunWasmLiftoff_Int32Clz fails on all targets

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#576]
Link to the offending bot: https://v8.imgtec.com/bbv8/builders/Sim%20-%20Debug%20-%20edge/builds/16162/steps/Check/logs/RunWasmLiftoff_Int32Clz

**Comment by sretenkovacevic** [comment]
When liftoff binop for Clz has been introduced (not implemented yet), bailout to turbofan was disabled by mistake. [https://chromium-review.googlesource.com/c/v8/v8/+/918722](https://chromium-review.googlesource.com/c/v8/v8/+/918722) this commit fixed bailout to turbofan. After that, this instruction has been implemented in liftoff with the following commit: [https://chromium-review.googlesource.com/c/v8/v8/+/919161](https://chromium-review.googlesource.com/c/v8/v8/+/919161).

Since everything works fine now, this issue can be closed.

**Comment by ibogosavljevic** [comment]
Closed
