### ISSUE TITLE
Update or remove obsolete GYP builders

### ISSUE THREAD

**Issue by MIPSbkirby** [v8mips/v8mips#578]
It looks like upstream has removed GYP configuration from V8.  We still have builders that use GYP for configuration.  Specifically, the following builders still use it:

- Target - edge - clang,mipsr1 - builder
- Target - edge - shared library - builder
- Sim - Debug - edge - GYP
- Sim - MIPS64 - Debug - edge - GYP

Since these builders no longer work as is, should we remove them?  If not, please let me know how to get them building again.  The first one could be switched to GN, but it looks like that still doesn't work for that builder.  The second one requires a configuration to turn on the shared library in GN in order to switch it.  The last two were intended to be used to make sure we knew the state of the GYP builds and so they can probably be removed.

**Comment by ibogosavljevic** [comment]
GYP is removed from the V8 upstream so we cannot use it anymore. So please put aside Sim -Debug and Sim - MIPS64 - Debug builders (I didn't say delete because I am still investigating node.js and v8)

As far as Target builders are concerned, those need to be migrated to GN. For the shared library builder, you use the same configuration as regular Release builder, but add a line is_component_build=true in the GN configure line.

mipsr1 with CLANG is a hard nut, we will need to investigate on how to fix it.

Creating issue for mipsr1 with clang and closing this one.
