### ISSUE TITLE
Unnecessary t9 usage before j, jal jumps.

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#75]
runnig d8 with --print-all-code shows a lot of

```
lui t9, <addr1>; ori t9, t9, <addr2>; j[al] <addr1_addr2>
```

like

```
0x4f578608   104  3c194f50       lui     t9, 0x4f50          ;; code: STUB, StoreBufferOverflowStub, minor: 1
0x4f57860c   108  3739f280       ori     t9, t9, 0xf280
0x4f578610   112  0fd43ca0       jal     0xf50f280
```

instruction sequences where the t9 usage seems to be unnecessary.

**Comment by petar-jovanovic** [comment]
Isn't this the optimization from - IIRC - set_target_address_at()?

**Comment by paul99** [comment]
Good memory, Petar, exactly right. Balázs, this is good observation, and there is _possibly_ a small further optimization that could be done, if you want to benchmark it. Please see all code in `Assembler::set_target_address_at()` and `Assembler::target_address_at()`.

A standard call consists of `lui t9; ori t9; jalr t9; nop`. MIPS has a weird instruction `jal` which encodes 26-bits of direct address, that when shifted allows a 28-bit jump target. But rather than a signed displacement, it is encoded as an absolute address within the same 256 MB code page that you jumped from. So if your source and destination are in the same 256 MB page, we replace the (slower) `jalr t9` with a (faster) `jal <address>`, when the address is patched (and it is patched when the code is first moved into place right after generation.)

However, gc can and does move code around. So an address that makes the 256MB page restriction may get patched to another that does not, so we must then revert to patching the address in `lui; ori`, and replacing the `jal` with `jalr t9`.

Clearly we must have left space in the code to do that. Presently, we leave the `lui; ori` in place, and it leaves the non-used case you observed. We could have patched them with `nop`. That might prove to be slightly faster, and you could benchmark that. Opinions on our HW team were that it would not help much, but they are opinions, and have never been checked by benchmarking. So give it a try. (You would have to then fix `Assembler::target_address_at()` to extract the address from the pc_ and `jal`.) 

Note that there is also a Jump() variant using `jr` and a `j`. Also note that some cores had a bug where `jal` did the wrong thing when its address was with 32KB of the start or end of a 256MB page. There is a workaround enabled currently for ALL cores, since it was not easy to determine core type. There is also a funny boundary condition when the `jal` and delay slot are right at boundary, read the manual carefully.

Finally, this optimization was a big win for 24K class cores (probably including Ingenic 801). The newer cores have a jr prediction cache and get much better performance out of `jalr`, so the improvement has less effectiveness.

**Comment by paul99** [comment]
Explanation given. Not a bug.
