### ISSUE TITLE
GYP compilation for native MIPS target

### ISSUE THREAD

**Issue by kalmard** [v8mips/v8mips#9]
Our wiki (https://github.com/paul99/v8m-rb/wiki/Building-v8-for-MIPS-with-GYP) explains how to compile to MIPS HW using gyp but it is wrong.

ia32 is automatically set as the target arch in build/mipsu.gypi (the arm version also sets this) which implies simulator usage. I found no way to compile to native MIPS (or ARM) without either modifying mipsu.gypi or running gyp manually with custom defines.

A related note:
Makefile has a target called "native" which is currently the host system, but maybe it could be extended to detect the target based on the compiler's version (and thus compile to MIPS if CC/CXX is set properly).

**Comment by paul99** [comment]
Dusan, can you please take a look at this, and let us know the status? 

I do remember a similar issue of target ia32 were trying to get GYP-based build working in GH issue 3 (now closed). Ultimately the requester was trying to build big-endian, but I could not get anything to cross-compile, even little-endian.

**Comment by dusmil** [comment]
Yes, the make file wrapper for gyp (file "Makefile' in v8 root dir)  does not support cross compile from start, although gyp config files are ready for cross-compiling  for mips target. Because of this, we always had to edit mipsu.gypi file before we export env. variables and run "make mips.release" command.

I have made some changes in wrapper ( patch is on dm-dev-gyp) and add "cross" target similarly as "native"  target exist.
With this change we can easely do cross-build with  "make cross target=mips" command after we export variables for toolchain (CC, CXX, ..).  This can be universal way to support cross build  for any target through gyp makefile wrapper. Please, take a look, if the approach in patch is accepted  I will update wiki page immediately.

**Comment by dusmil** [comment]
OK, I have updated the patch on dm-dev-gyp branch, now we can switch to debug mode with command as:

make cross target=mips BUILDTYPE=Debug 

and analog for native build

make native BUILDTYPE=Debug

Release mode is still default.

**Comment by kalmard** [comment]
It turned out that cross-compilation is supported for ARM - the secret is that we also need to set up the $LINK variable (same as $CXX) - then "make arm" works like a charm.

However the same solution doesn't work for MIPS. Luckily Jakob (jkummerow) offered to help us with this - see the discussion at http://codereview.chromium.org/10257030/ .

**Comment by paul99** [comment]
Dusan - There is new discussion at http://codereview.chromium.org/10257030/ and per comment there, Jakob has pushed a new patch at https://chromiumcodereview.appspot.com/10268010. Can you please look at that one....

**Comment by paul99** [comment]
Hi Gergely, Akos - Dusan is on holiday, can you guys please test the version in https://chromiumcodereview.appspot.com/10268010, and comment back to Jakob either on that issue, or on http://codereview.chromium.org/10257030/ ?

**Comment by palfia** [comment]
Commented at: https://chromiumcodereview.appspot.com/10268010

**Comment by paul99** [comment]
The referenced commit was landed, the gyp support for mips has been updated several times since this issue, and works fine at this time. Closing.
